import type { Metadata } from 'next';
import { Urbanist } from 'next/font/google';
import './globals.css';

const ubranist = Urbanist({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={ubranist.className}>{children}</body>
    </html>
  );
}
